services:
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: pdsl-06-php
    ports:
      - "816:8080"

  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: pdsl-06-node
    ports:
      - "826:8080"

  python:
    build:
      context: ./python
      dockerfile: Dockerfile
    container_name: pdsl-06-python
    ports:
      - "836:8080"

  java:
    build:
      context: ./java
      dockerfile: Dockerfile
    container_name: pdsl-06-java
    ports:
      - "846:8080"

  dotnet:
    build:
      context: ./dotnet
      dockerfile: Dockerfile
    container_name: pdsl-06-dotnet
    ports:
      - "856:8080"
