services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pdsl-01-node-app
    ports:
      - "821:8080"
    healthcheck:
      test: ["CMD", "node", "-e", "process.exit(0)"]
      interval: 10s
      timeout: 3s
      retries: 3
