services:
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: pdsl-05-php
    ports:
      - "815:8080"

  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: pdsl-05-node
    ports:
      - "825:8080"

  python:
    build:
      context: ./python
      dockerfile: Dockerfile
    container_name: pdsl-05-python
    ports:
      - "835:8080"

  java:
    build:
      context: ./java
      dockerfile: Dockerfile
    container_name: pdsl-05-java
    ports:
      - "845:8080"

  dotnet:
    build:
      context: ./dotnet
      dockerfile: Dockerfile
    container_name: pdsl-05-dotnet
    ports:
      - "855:8080"
