services:
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: pdsl-02-php
    ports:
      - "812:8080"

  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: pdsl-02-node
    ports:
      - "822:8080"

  python:
    build:
      context: ./python
      dockerfile: Dockerfile
    container_name: pdsl-02-python
    ports:
      - "832:8080"

  java:
    build:
      context: ./java
      dockerfile: Dockerfile
    container_name: pdsl-02-java
    ports:
      - "842:8080"

  dotnet:
    build:
      context: ./dotnet
      dockerfile: Dockerfile
    container_name: pdsl-02-dotnet
    ports:
      - "852:8080"
