services:
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: pdsl-20-php
    ports:
      - "8120:8080"

  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: pdsl-20-node
    ports:
      - "8220:8080"

  python:
    build:
      context: ./python
      dockerfile: Dockerfile
    container_name: pdsl-20-python
    ports:
      - "8320:8080"

  java:
    build:
      context: ./java
      dockerfile: Dockerfile
    container_name: pdsl-20-java
    ports:
      - "8420:8080"

  dotnet:
    build:
      context: ./dotnet
      dockerfile: Dockerfile
    container_name: pdsl-20-dotnet
    ports:
      - "8520:8080"

  go:
    build:
      context: ./go
      dockerfile: Dockerfile
    container_name: pdsl-20-go
    ports:
      - "8620:8080"

  rust:
    build:
      context: ./rust
      dockerfile: Dockerfile
    container_name: pdsl-20-rust
    ports:
      - "8720:8080"
