services:
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: pdsl-11-php
    ports:
      - "8111:8080"

  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: pdsl-11-node
    ports:
      - "8211:8080"

  python:
    build:
      context: ./python
      dockerfile: Dockerfile
    container_name: pdsl-11-python
    ports:
      - "8311:8080"

  java:
    build:
      context: ./java
      dockerfile: Dockerfile
    container_name: pdsl-11-java
    ports:
      - "8411:8080"

  dotnet:
    build:
      context: ./dotnet
      dockerfile: Dockerfile
    container_name: pdsl-11-dotnet
    ports:
      - "8511:8080"
