services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pdsl-04-java-app
    ports:
      - "844:8080"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8080/health > /dev/null || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 15s
