services:
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: pdsl-12-php
    ports:
      - "8112:8080"

  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: pdsl-12-node
    ports:
      - "8212:8080"

  python:
    build:
      context: ./python
      dockerfile: Dockerfile
    container_name: pdsl-12-python
    ports:
      - "8312:8080"

  java:
    build:
      context: ./java
      dockerfile: Dockerfile
    container_name: pdsl-12-java
    ports:
      - "8412:8080"

  dotnet:
    build:
      context: ./dotnet
      dockerfile: Dockerfile
    container_name: pdsl-12-dotnet
    ports:
      - "8512:8080"
