services:
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: pdsl-03-php
    ports:
      - "813:8080"

  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: pdsl-03-node
    ports:
      - "823:8080"

  python:
    build:
      context: ./python
      dockerfile: Dockerfile
    container_name: pdsl-03-python
    ports:
      - "833:8080"

  java:
    build:
      context: ./java
      dockerfile: Dockerfile
    container_name: pdsl-03-java
    ports:
      - "843:8080"

  dotnet:
    build:
      context: ./dotnet
      dockerfile: Dockerfile
    container_name: pdsl-03-dotnet
    ports:
      - "853:8080"
