services:
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: pdsl-09-php
    ports:
      - "819:8080"

  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: pdsl-09-node
    ports:
      - "829:8080"

  python:
    build:
      context: ./python
      dockerfile: Dockerfile
    container_name: pdsl-09-python
    ports:
      - "839:8080"

  java:
    build:
      context: ./java
      dockerfile: Dockerfile
    container_name: pdsl-09-java
    ports:
      - "849:8080"

  dotnet:
    build:
      context: ./dotnet
      dockerfile: Dockerfile
    container_name: pdsl-09-dotnet
    ports:
      - "859:8080"
