services:
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: pdsl-04-php
    ports:
      - "814:8080"

  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: pdsl-04-node
    ports:
      - "824:8080"

  python:
    build:
      context: ./python
      dockerfile: Dockerfile
    container_name: pdsl-04-python
    ports:
      - "834:8080"

  java:
    build:
      context: ./java
      dockerfile: Dockerfile
    container_name: pdsl-04-java
    ports:
      - "844:8080"

  dotnet:
    build:
      context: ./dotnet
      dockerfile: Dockerfile
    container_name: pdsl-04-dotnet
    ports:
      - "854:8080"
