services:
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: pdsl-18-php
    ports:
      - "8118:8080"

  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: pdsl-18-node
    ports:
      - "8218:8080"

  python:
    build:
      context: ./python
      dockerfile: Dockerfile
    container_name: pdsl-18-python
    ports:
      - "8318:8080"

  java:
    build:
      context: ./java
      dockerfile: Dockerfile
    container_name: pdsl-18-java
    ports:
      - "8418:8080"

  dotnet:
    build:
      context: ./dotnet
      dockerfile: Dockerfile
    container_name: pdsl-18-dotnet
    ports:
      - "8518:8080"

  go:
    build:
      context: ./go
      dockerfile: Dockerfile
    container_name: pdsl-18-go
    ports:
      - "8618:8080"

  rust:
    build:
      context: ./rust
      dockerfile: Dockerfile
    container_name: pdsl-18-rust
    ports:
      - "8718:8080"
