services:
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: pdsl-07-php
    ports:
      - "817:8080"

  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: pdsl-07-node
    ports:
      - "827:8080"

  python:
    build:
      context: ./python
      dockerfile: Dockerfile
    container_name: pdsl-07-python
    ports:
      - "837:8080"

  java:
    build:
      context: ./java
      dockerfile: Dockerfile
    container_name: pdsl-07-java
    ports:
      - "847:8080"

  dotnet:
    build:
      context: ./dotnet
      dockerfile: Dockerfile
    container_name: pdsl-07-dotnet
    ports:
      - "857:8080"
