services:
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: pdsl-15-php
    ports:
      - "8115:8080"

  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: pdsl-15-node
    ports:
      - "8215:8080"

  python:
    build:
      context: ./python
      dockerfile: Dockerfile
    container_name: pdsl-15-python
    ports:
      - "8315:8080"

  java:
    build:
      context: ./java
      dockerfile: Dockerfile
    container_name: pdsl-15-java
    ports:
      - "8415:8080"

  dotnet:
    build:
      context: ./dotnet
      dockerfile: Dockerfile
    container_name: pdsl-15-dotnet
    ports:
      - "8515:8080"

  go:
    build:
      context: ./go
      dockerfile: Dockerfile
    container_name: pdsl-15-go
    ports:
      - "8615:8080"

  rust:
    build:
      context: ./rust
      dockerfile: Dockerfile
    container_name: pdsl-15-rust
    ports:
      - "8715:8080"
